# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ heroku ]
  pull_request:
    branches: [ heroku ]

jobs:
  test:
    environment: imazen-licensing
    env: # Or as an environment variable
      TEST_LICENSE_SIGNING_KEY_PASSPHRASE: ${{ secrets.TEST_LICENSE_SIGNING_KEY_PASSPHRASE }}
      TEST_LICENSE_SIGNING_KEY_BLOB: ${{ secrets.TEST_LICENSE_SIGNING_KEY_BLOB }}
      LICENSE_S3_ID: ${{ secrets.LICENSE_S3_ID }}
      LICENSE_S3_SECRET: ${{ secrets.LICENSE_S3_SECRET }}
      CHARGEBEE_SITE: ${{ secrets.CHARGEBEE_SITE }}
      CHARGEBEE_API_KEY: ${{ secrets.CHARGEBEE_API_KEY }}
      CHARGEBEE_WEBHOOK_TOKEN: ${{ secrets.CHARGEBEE_WEBHOOK_TOKEN }}
      LICENSE_SECRET_SEED: ${{ secrets.LICENSE_SECRET_SEED }}
    
    
    runs-on: ubuntu-latest

    steps:
    - name: Check for CHARGEBEE_SITE
      run: if [[ -z "${CHARGEBEE_SITE}" ]]; then exit 1; fi
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6.6
    - name: Install dependencies
      run: bundle
    - name: Run tests
      run: bundle exec rake
    - name: Run gem tests
      run: cd gem; bundle; rake
